// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tauxtmfgmlxkuzvmfvtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhdXh0bWZnbWx4a3V6dm1mdnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxODU0MjQsImV4cCI6MjA2Nzc2MTQyNH0.Ugs3oDHqig7CnrO-ZDpnyc4akYHv9Rh3UPubWP-OM64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});